#cloud-config
autoinstall:
  version: 1
  locale: en_US
  storage:
    config:
      - id: disk0
        type: disk
        ptable: gpt
        match:
          size: largest
          ssd: true
        preserve: false
        grub_device: true
      - type: partition
        id: boot-partition
        device: disk0
        size: 512M
        flag: boot
        partition_type: EF00
        wipe: superblock
        preserve: false
        grub_device: true
      - id: lvm_partition_data
        type: partition
        size: -1
        device: disk0
      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices: [lvm_partition_data]
      - id: lvroot
        type: lvm_partition
        name: lvroot
        volgroup: vg0
        size: 100G
      - id: lvhome
        type: lvm_partition
        name: lvhome
        volgroup: vg0
        size: -1
      - id: mount_root
        type: mount
        path: /
        device: lvroot
      - id: mount_home
        type: mount
        path: /home
        device: lvhome

    config:
      - type: disk                   # Always install OS on our smallest disk
        match:
          size: smallest
        id: os-drive
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: false
      - type: partition             # EFI partition /boot/efi
        number: 1
        id: efi-partition
        device: os-drive
        size: 256M
        flag: boot
        grub_device: true
      - type: format                # EFI partition format rules
        id: efi-format
        volume: efi-partition
        fstype: fat32
        label: ESP
      - path: /boot/efi             # EFI partition mount rules
        device: efi-format
        type: mount
        id: mount-efi
      - type: partition             # BOOT partition /boot
        number: 2
        id: boot-partition
        device: os-drive
        size: 1G
        grub_device: false
      - type: format                # BOOT partition format rules  
        id: boot-format
        volume: boot-partition
        fstype: ext4
        label: BOOT
      - path: /boot                 # BOOT partition mount rules
        device: boot-format
        type: mount
        id: mount-boot
      - type: partition             # LVM partition (PV)
        number: 3
        id: lvm-partition
        device: os-drive
        size: -1
        grub_device: false
      - name: system                # LVM VG (system)
        devices:
        - lvm-partition
        preserve: false
        type: lvm_volgroup
        id: lvm_volgroup-0
      - name: root                  # LVM LV (root)
        volgroup: lvm_volgroup-0
        size: 16G
        wipe: superblock
        preserve: false
        type: lvm_partition
        id: lvm_partition-root
      - fstype: xfs                 # LVM LV root - format rules
        volume: lvm_partition-root
        preserve: false
        type: format
        id: format-root
      - path: /                     # LVM LV root - mount rules
        device: format-root
        type: mount
        id: mount-root
    swap:
      swap: 0

  # Installs the default ubuntu-desktop packages.
  # You can add additional packages if required.
  packages:
    - ubuntu-desktop

  # Sets up SSH server and authorizes a key for remote access.
  ssh:
    install-server: true
    authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIXzBWhyNmrpXT9yN+RgAyS1mQ6tapm3G80Znp2Q9I6oAVNrKOB5BVazb7X3e7atNMXQgm6QQYsMZzoii+DSHgrmgHQ160vihtsvwmFFRxHb8fsmo0+9cH/lMoDhxWIk+Q9bLe+bqcGxAywD3EO1qgytUcmTOPjFIDyuU+cngb9TWvhJosZaZ0J8CwfzlJAYyItD0IP7fTqlUl079UU3lkU19DC3ocX+nx0q0glofnhCeSTll12H+BuPTMcPW9AKezkk8rgHlT0F8awGXmUfDj2tBFcCPrS1uyAJILU5iLKTc1oeELsIZFeUuSDNu2px+L8EKbhcnGWnbu3j5BSbHX ibobko@localhost.localdomain

  # User setup
  identity:
    username: nox
    password: $6$Jd6zyTUa/TGBXgtd$cOJ8pWsZxaKDU1SAo6qX32AMtH3WRIBTqIEbBvAmJGcQ7i.kmr5IkMUuuclWjpNVw9jmkUJfaLhe0j3m1TNeE/
    hostname: nox-home-laptop

  late-commands:
    # Configures GRUB for a quiet splash screen on boot.
    - curtin in-target -- sed -i /etc/default/grub -e 's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
