#cloud-config
autoinstall:
  version: 1
  locale: en_US
  storage:
    config:
      - id: disk0
        type: disk
        ptable: gpt
        path: /dev/nvme0n1
        preserve: false
        grub_device: true
      - id: boot_efi
        type: partition
        size: 1G
        device: disk0
        flag: boot
      - id: boot
        type: partition
        size: 2G
        device: disk0
      - id: lvm_partition_data
        type: partition
        size: -1
        device: disk0
      - id: vg0
        type: lvm_volgroup
        devices: [lvm_partition_data]
      - id: lvroot
        type: lvm_partition
        name: lvroot
        volgroup: vg0
        size: 100G
      - id: lvhome
        type: lvm_partition
        name: lvhome
        volgroup: vg0
        size: -1
      - id: mount_root
        type: mount
        path: /
        device: lvroot
      - id: mount_home
        type: mount
        path: /home
        device: lvhome

  # Installs the default ubuntu-desktop packages.
  # You can add additional packages if required.
  packages:
    - ubuntu-desktop

  # Sets up SSH server and authorizes a key for remote access.
  ssh:
    install-server: true
    authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIXzBWhyNmrpXT9yN+RgAyS1mQ6tapm3G80Znp2Q9I6oAVNrKOB5BVazb7X3e7atNMXQgm6QQYsMZzoii+DSHgrmgHQ160vihtsvwmFFRxHb8fsmo0+9cH/lMoDhxWIk+Q9bLe+bqcGxAywD3EO1qgytUcmTOPjFIDyuU+cngb9TWvhJosZaZ0J8CwfzlJAYyItD0IP7fTqlUl079UU3lkU19DC3ocX+nx0q0glofnhCeSTll12H+BuPTMcPW9AKezkk8rgHlT0F8awGXmUfDj2tBFcCPrS1uyAJILU5iLKTc1oeELsIZFeUuSDNu2px+L8EKbhcnGWnbu3j5BSbHX ibobko@localhost.localdomain

  # User setup
  identity:
    username: nox
    password: $6$Jd6zyTUa/TGBXgtd$cOJ8pWsZxaKDU1SAo6qX32AMtH3WRIBTqIEbBvAmJGcQ7i.kmr5IkMUuuclWjpNVw9jmkUJfaLhe0j3m1TNeE/
    hostname: nox-home-laptop

  late-commands:
    # Configures GRUB for a quiet splash screen on boot.
    - curtin in-target -- sed -i /etc/default/grub -e 's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
